esphome:
  name: dzwonek
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: !secret dzwonek
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dzwonek Fallback Hotspot"
    password: !secret api_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret api_password


web_server:
  port: 80

time:

  - platform: homeassistant
    id: homeassistant_time

text_sensor:

  - platform: version
    name: Dzwonek ESPHome Version
    
  - platform: wifi_info
    ip_address:
      name: Dzwonek IP
    ssid:
      name: Dzwonek SSID
    bssid:
      name: Dzwonek BSSID

sensor:
  - platform: uptime
    name: Dzwonek Uptime

  - platform: wifi_signal
    name: Dzwonek WiFi Signal
    update_interval: 60s

switch:
  - platform: restart
    name: Dzwonek Restart

  - platform: gpio
    name: Dzwonek Przelacznik
    pin: D2

binary_sensor:

  - platform: gpio
    id: button
    name: Dzwonek Przycisk
    pin:
      number: D1 
      mode: INPUT
      inverted: false
    filters:
      - invert:
      - delayed_on: 25ms
      - delayed_off: 2s
